# Generated by Django 5.1.4 on 2026-06-17 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Stable machine identifier, e.g. 'eis', 'sberbank_ast'.", unique=True)),
                ('name', models.CharField(max_length=200)),
                ('adapter_key', models.CharField(blank=True, help_text='Key under which the adapter is registered. Defaults to `code`.', max_length=50)),
                ('website_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='If off, this source is never polled and never displayed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSourcePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_source_permissions', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='sources.source')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['source__name'],
                'unique_together': {('user', 'source')},
            },
        ),
    ]
