# Generated by Django 5.1.4 on 2026-06-17 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Stable id of the tender within its source (e.g. EIS regNumber).', max_length=255)),
                ('number', models.CharField(blank=True, max_length=100)),
                ('title', models.TextField()),
                ('customer', models.CharField(blank=True, max_length=500)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Initial (maximum) contract price (NMC), if known.', max_digits=18, null=True)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('fz_type', models.CharField(blank=True, choices=[('44', '44-ФЗ'), ('223', '223-ФЗ'), ('', 'Прочее / н.д.')], default='', max_length=8)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='sources.source')),
            ],
            options={
                'ordering': ['-published_at', '-first_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenders.tender')),
            ],
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['region'], name='tenders_ten_region_8aae36_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['fz_type'], name='tenders_ten_fz_type_123133_idx'),
        ),
        migrations.AddIndex(
            model_name='tender',
            index=models.Index(fields=['-published_at'], name='tenders_ten_publish_19c16d_idx'),
        ),
        migrations.AddConstraint(
            model_name='tender',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_tender_per_source'),
        ),
        migrations.AddConstraint(
            model_name='tenderdocument',
            constraint=models.UniqueConstraint(fields=('tender', 'url'), name='uniq_document_per_tender'),
        ),
    ]
