# Generated by Django 5.1.4 on 2026-06-17 17:19

import apps.tenders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderdocument',
            name='content_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tenderdocument',
            name='download_error',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='tenderdocument',
            name='fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenderdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.tenders.models.tender_document_path),
        ),
        migrations.AddField(
            model_name='tenderdocument',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenderdocument',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
